---
name: Create a new VM from a template
hosts: localhost
gather_facts: false
tasks:
  - name: Clone the template
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ datacenter }}"
      folder: "/{{ datacenter }}/vm/{{ folder }}"
      name: "{{ vm_name }}"
      state: poweredon
      template: "{{ template }}"
      disk:
      - size_gb: "{{ disk_size_gb }}"
        type: thin
        datastore: "{{ datastore }}"
      hardware:
        memory_mb: "{{ memory_mb }}"
        num_cpus: "{{ num_cpus }}"
      networks:
      - name: "{{ network }}"
        device_type: vmxnet3
      customization:
        existing_vm: "{{ customization_spec }}"
